### ISSUE TITLE
Add message.yml 

### ISSUE THREAD

**Issue by VoChiDanh** [dmccoystephenson/SimpleSkills#64]
Why do I need to add it? I thought I would add it because it can help other language users to translate their language for their server.
- [x] Add reload command
- [x] Commands
- [x] Small change with config
- [x] Message
- [x] Other...

**Comment by VoChiDanh** [comment]
maybe it will be completed after I finish the semester exam :0

**Comment by dmccoystephenson** [comment]
Sounds good! Localization is a feature of Medieval Factions and I have implemented a locale service class in the Ponder library, so you can check that out if you want to. Might be of use 😉

**Comment by VoChiDanh** [comment]
Maybe I'll do it another way  ~~

**Comment by dmccoystephenson** [comment]
Totally fine if you want to do it another way 👍 I look forward to it

**Comment by VoChiDanh** [comment]
#65 ty :3
